---
title: '2019-09-21'
author: ''
date: '2019-09-21'
slug: rede-social-partidos
categories: []
tags: []
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r}
load("first-post/programas_df.RData")

library(dplyr)


ps <- c("\\bps\\b", "\\bpartido socialista\\b")
psd <- c("\\bpsd\\b", "\\bpartido social democratico\\b")
cds <- c("\\bcds\\b", "\\bcds-pp\\b", "\\bPartido do Centro Democrático e Social\\b")
be <- c("\\bbe\\b", "\\bbloco\\b", "\\bbloco de esquerda\\b", "\\bbloco esquerda\\b")
pan <- c("\\bpan\\b", "\\bpessoas animais natureza\\b")
pcp <- c("\\bpcp\\b", "\\bpartido comunista portugues\\b", "\\bpartido comunista\\b")
os_verdes <- c("\\bos verdes\\b")

occurrences <- function(data){
  data %>% 
    mutate(ps = sum(stringr::str_count(text, ps)),
           psd = sum(stringr::str_count(text, psd)),
           cds = sum(stringr::str_count(text, cds)),
           be = sum(stringr::str_count(text, be)),
           pan = sum(stringr::str_count(text, pan)),
           pcp = sum(stringr::str_count(text, pcp)),
           os_verdes = sum(stringr::str_count(text, os_verdes))
    ) %>% 
    select(-text)
}

relations <- purrr::map_df(c("ps", "psd", "cds", "be", "pan", "pcp", "verdes"), function(x) {occurrences(programas_df_renamed %>% filter(doc_id == x))}) %>% select(-doc_id) %>% as.matrix() 
diag(relations) <- 0

library(igraph)
library(visNetwork)

set.seed(3)
g <- graph_from_adjacency_matrix(relations, weighted = TRUE)

# c_scale <- colorRamp(c("darkgreen", "yellow","red"), interpolate = "spline")
# E(g)$color <- apply(c_scale(scale(E(g)$weight)), 1, function(x) ifelse(is.na(x[1]) || is.na(x[2]) || is.na(x[3]), rgb(1,1,1), rgb(x[1]/255,x[2]/255,x[3]/255)))
    
g %>%
  visNetwork::visIgraph() %>% 
  visIgraphLayout() %>%
  visNodes(
    shape = "dot",
    color = list(
      background = "#0085AF",
      border = "#013848",
      highlight = "#FF8000"
    ),
    shadow = list(enabled = TRUE, size = 10)
  ) %>%
  visEdges(
    shadow = FALSE,
    color = list(color = "#0085AF", highlight = "#C62F4B")
  ) %>%
  visOptions(highlightNearest = list(enabled = T, degree = 1, hover = T)) %>% 
  visLayout(randomSeed = 11)

g %>% 
  visNetwork::visIgraph() 
```

